[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
test = "test"
cache_path = "cache"
optimizer = true
optimizer_runs = 200
via_ir = true
solc = "0.8.19"
fs_permissions = [{ access = "read", path = "./" }]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=node_modules/forge-std/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
