[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
optimizer = true
optimizer_runs = 200
via_ir = true
solc = "0.8.24"
fs_permissions = [{ access = "read", path = "./" }]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
